--- 
language: node_js
node_js: 
  - node
  - iojs
  - "0.12"
  - "iojs-v2.0"
  - "iojs-v2.1"
before_script:
  - rm -rf ./coverage
  - npm run lint 2>/dev/null
after_script:
  - test -e ./coverage/lcov.info && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
env:
  global:
    COVERALLS_SERVICE_NAME: travis-ci
    COVERALLS_REPO_TOKEN: FvloHR8QKMNlY0zQrSzgRa48J3GJ5KhBO